### ISSUE TITLE
Logo is not rendering

### ISSUE THREAD

**Issue by igoras1993** [Raider-Arts/sphinx-uedoc-theme#1]
Hi, nice theme.

You have used (probably) wrong variable in `header.html` template in `if` clause ([here](https://github.com/Raider-Arts/sphinx-uedoc-theme/blob/2550c38466fd56f5524aa66567e18499a9ef0e8b/src/static/header.html#L21)). 

I am assuming that instead of `logo`, one should use `theme_logo`.

**Comment by igoras1993** [comment]
I've created a PR fith a fix: https://github.com/Raider-Arts/sphinx-uedoc-theme/pull/2

**Comment by faggionluca** [comment]
Thank you again for the fix, sorry again for the late reply (merged #2)
